config/routes.rb
Rails.application.routes.draw do
  get 'help/learn_more'
  scope '/(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :room_messages
    resources :rooms
    root to: 'help#learn_more'
    devise_for :users, :path_prefix => 'd', controllers: {
      sessions: 'users/sessions',
    }
    
    resources :posts
    get 'users/:id' => 'users#show'
    resources :users, :only => [:show]
    resources :users do 
      resources :feedbacks
    end
    resources :room_messages
    resources :rooms
    resources :categories
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  validates :email, uniqueness: true, presence: true
  validates :first_name, uniqueness: false, presence: true
  validates :second_name, uniqueness: false, presence: true

  has_many :posts, dependent: :destroy
  has_many :feedbacks
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  def show
  end
  
  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @posts = Post.paginate(page: params[:page], per_page: 3)
        # @paginate_check = false
        return @posts, @user
    end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<link rel="stylesheet" href="posts.scss">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.6.95/css/materialdesignicons.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
<link rel="stylesheet" href="post.css">
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="col-xl-6 col-md-12" style="margin:0 auto;">
            <div class="card user-card-full">
                <div class="row m-l-0 m-r-0">
                    <div class="col-sm-4 bg-c-lite-green user-profile">
                        <div class="card-block text-center text-white">
                            <div class="m-b-25"> <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius" alt="User-Profile-Image"> </div>
                            <h6 class="f-w-600"><%= @user.first_name %> <%= @user.second_name %></h6>
                            <% if user_signed_in? %>
                                <%if  @user.id == current_user.id %>
                                <a class="edit-li">  <%= link_to t('common.Edit_profile'), edit_user_registration_path, :class => 'edit-btn' %> </li>
                                <% else %>
                                <a class="edit-li">  <%= link_to t('common.Message_me'), new_room_path(
                                                                                    :user_id => @user.id,
                                                                                    :first_name => @user.first_name,
                                                                                    :second_name => @user.second_name
                                                                                    ), :class => 'edit-btn'%> </li>
                                
                                <% end %>
                            <% end %>
                                <!-- <p>Web Designer</p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i> -->
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="card-block">
                            <h6 class="m-b-20 p-b-5 b-b-default f-w-600"><%= t('common.Information') %></h6>
                            <div class="row">
                                <div class="col-sm-6">
                                    <p class="m-b-10 f-w-600"><%= t('common.First_name') %></p>
                                    <h6 class="text-muted f-w-400"><%= @user.first_name %></h6>
                                </div>
                                <div class="col-sm-6">
                                    <p class="m-b-10 f-w-600"><%= t('common.Second_name') %></p>
                                    <h6 class="text-muted f-w-400"><%= @user.second_name %></h6>
                                </div>
                                <% if current_user %>
                                    <% if current_user.id == @user.id %>
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600"><%= t('common.email')%></p>
                                            <h6 class="text-muted f-w-400"><%= @user.email %></h6>
                                        </div>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        
<!--Posts on profile page (можно будет потом сделать условно посты справа от профиля, а не под)-->
<div class="main-body">
    <% @posts.each do |post| %>
        
        <% if post.owner_id == @user.id %>
            <% @paginate_check = true %>
            <div class="profile-post">
                <%= image_tag post.image.url(:thumb), class: 'mini-img-class' if post.image? %>
                <div class="profile-post-data">
                    <h3><%= link_to post.title, post_path(post) %></h3>
                    <div class="price">
                        <b><%= post.price %> PLN</b>
                        <small><%= post.created_at %></small>
                    </div>
                    <div class="block-with-text">
                        <%= post.body %>
                    </div>
                </div>
        </div>
        <% end %>

    <% end %>
        <% if @paginate_check %>
                <%= will_paginate @posts %>
        <%end%>
</div>

        <%= form_for ([@user, @user.feedbacks.build])  do |form| %>

            <h2>FEEDBACK</h2>
                <div class="form-group">
                    <%= form.text_field :title, class:"input", placeholder:t("posts.new.post_name")%>  
                </div>
              <div class="form-group">
                <%= form.text_area :body, class: 'input', style:'border: 1px solid black;' %>
              </div>
                <%= hidden_field_tag(:user, @user.id) %>

              <div class="form-group">
                <%= form.submit  t('common.add_comment'), class: 'btn btn-primary'%>
              </div>
            <% end %>
            <% if @user.feedbacks.exists? %>
              <% @user.feedbacks.each do |feedback| %>
            <h4><%= feedback.title %> (<%= link_to 'Creator', user_url(User.all.where(user_id: feedback.owner_id)) %>)<h4>
                <section class = 'comment-summary'>
                <%= feedback.body %>
                </section>
            <% end %>
            <% end %>
            