config/routes.rb
Rails.application.routes.draw do
  get 'help/learn_more'
  scope '/(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :room_messages
    resources :rooms
    root to: 'help#learn_more'
    devise_for :users, :path_prefix => 'd', controllers: {
      sessions: 'users/sessions',
    }
    
    resources :posts
    get 'users/:id' => 'users#show'
    resources :users, :only => [:show]
    resources :users do 
      resources :feedbacks
    end
    resources :room_messages
    resources :rooms
    resources :categories
  end
end

app/models/post.rb
class Post < ApplicationRecord
    # belongs_to :user
    belongs_to :category
    
    mount_uploader :image, ImageUploader
    validates :title, :body, presence: true
    # has_many_attached :images 
    validates :price, presence: true

    validates :category, presence: false
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
    def index
      @posts = Post.paginate(page: params[:page], per_page: 5)
      @users = User.all
      @categories = Category.all
      return @posts, @users, @categories
    end
  
    def show
      @post = Post.find(params[:id])
    end
  
    def edit
      @post = Post.find(params[:id])
    end

    def new
      @post = Post.new      
    end

    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit
      end
    end

    def create
      @post = Post.new(post_params)
      @post.owner_id = current_user.id
      respond_to do |format|
        
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to root, notice: 'Post was successfully deleted.' }
        format.json { head :no_content }
      end
    end

    private
    

    def post_params
      params.require(:post).permit(
        :title,
        :body,
        :owner_id,
        :price,
        :image,
        :category_id,
        # :condition,
       )
    end

  end

app/views/posts/_delimeter.html.erb
<div class="page_delimeter">Page <%= params[:page] %></div>

app/views/posts/_form.html.erb
<link rel="stylesheet" href="posts.css">
<%= form_for @post,html: {multipart: true} do |f| %>
    <div class="form-group">
        <%= f.text_field :title, class:"input", placeholder:t("posts.new.post_name")%>  
    </div>
    
    <div class="form-group">
         <h5><%= f.label :price%></h5>
        <%= f.text_field :price, class:"input", type: "double"%>  
    </div>

    <div class="form-group">
        <h5><%= f.label :category_id %></h5>
        <%= f.collection_select :category_id, Category.order(:name), :id, :name, 
                                { include_blank: false }, class: 'input' %>
    </div>


    <div class="form-group">
        <h5><%= f.label :body%></h5>
        <%= f.text_area :body, class:"body-input", placeholder:t("posts.new.description") %>
    </div>

    <div class="form-group">
        <h5>Image</h5>
        <%= f.file_field :image, class:"input" %>
    </div>

    <div class="form-group">
        <%= f.submit t('common.Save'), class:"create-btn"%>
    </div>
 
<% end %>

app/views/posts/edit.html.erb
<head>
    <link rel="stylesheet" href="posts.css">
    <title>Edit announcement</title>
</head>
<div class="main-body">
    <div class="form-group">
        <h3> Edit ad</h3>
        <%= render 'form' %>
    </div>
</div>

app/views/posts/index.html.erb
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="posts.scss">
<div class="main-body">
  <% if false %>
    
    <div class="users">
      USERS:
      <% @users.each do |user| %>
      <%= link_to user.email, user_url(user.id), style: 'color: red' %>
      <% end %>
    </div>  
  <% end %>
  
  <% if true %>
    
    <div class="categories">
      <% @categories.each do |category| %>
        <%= link_to category.name, category_path(category),  class: 'category_link' %>
      <% end %>
    </div>  
  <% end %>

  <!-- Поставь тут иф, чтобы в ошибку не уходило когда нет постов -->

      <% @posts.each do |post| %>
        <div class="profile-post" id='posts' href="#ebhwjd">
          <%= image_tag post.image.url(:thumb), class: 'mini-img-class' if post.image? %>
          <div class="profile-post-data">
            <h3><%= link_to post.title, post_path(post) %></h3>
            <h5>
            <%= link_to  "#{@users.find(post.owner_id).first_name} #{@users.find(post.owner_id).second_name}",
                         user_url(post.owner_id) %></h5> <!-- Добавь тут Юзера а не протсо слово автор -->
            <div class="price">
              <p><%= post.price %> PLN</p>
              <small><%= post.created_at %></small>
            </div>
            <div class="block-with-text">
                  <%= post.body %>
            </div>
            
          </div>
        </div>


      <% end %>
      <%= will_paginate @posts, class: 'pagination' %>
    
</div>

app/views/posts/index.js.erb
$('#posts').append("<%= j render(partial: 'delimeter') %>");
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
    $('.pagination').replaceWith("<%= j  will_paginate(@posts) %>");
<% else %>
    $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="posts.css">
        <title>New announcement</title>
    </head>
    <div class="main-body">
        <div class="form-group">
            <% if user_signed_in? %>
                <h3><%= t('posts.new.title') %></h3>
                <%= render 'form' %>
            <% else %>
            <!--Гениальное решение, но нужно что-то другое-->
            <h2>Sign in pls</h2>
            <% end %>
        </div>
    </div>
</html>

app/views/posts/show.html.erb
<head>
  <link rel="stylesheet" href="posts.scss">
</head>
  <div class="main-body">
    <div class="announcement-full">
      <h1 style="text-align: center;"><%= @post.title %></h1>
      <%= image_tag @post.image.url(:large), class: 'img-class' if @post.image? %>
      <h3><%= @post.price %> PLN</h3><!--И конвертцию валют в теории можно добавить-->
      <% if false %>
      <h3><%= @post.condition %> ТУТ СОСТОЯНИЕ СДЕЛАЙ КРАСИВо</h3>
        думаю не трогай
      <% end %>

      <div class="main-block-with-text"><%= @post.body %></div>
      <small><%= @post.created_at.to_date %><!--Поменяй c UTC на норм время--></small>
      <div class="action">
        <% if @post.owner_id == current_user.id %>
        <%= link_to 'Edit', edit_post_path(@post), class: "create-btn" %>
        <br><br>
        <%else %>
        <%end%>
      </div>
    </div>
  </div>
<% if @post.owner_id == current_user.id %>
<%else %>
<%end%>