config/routes.rb
Rails.application.routes.draw do
  get 'help/learn_more'
  scope '/(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :room_messages
    resources :rooms
    root to: 'help#learn_more'
    devise_for :users, :path_prefix => 'd', controllers: {
      sessions: 'users/sessions',
    }
    
    resources :posts
    get 'users/:id' => 'users#show'
    resources :users, :only => [:show]
    resources :users do 
      resources :feedbacks
    end
    resources :room_messages
    resources :rooms
    resources :categories
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts

    validates :name, presence: true

    # has_ancestry  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    # before_action :set_category, only: :show
  
    def index
      @categories = Category.all
      
    end

    def show
      @posts = Post.all
      @category = Category.all.find(params[:id])
    end
  
    # private
  
    # def set_category
    #   @category = Category.find(params[:id])
    # end
end
  

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% @categories.each do |category| %>
    <%= link_to category.name, category_url(category.id) %>
    <% end %>

app/views/categories/show.html.erb
<% @posts.each do |post| %>
  <% if post.category_id == @category.id %>
      <div class="profile-post" id='posts' href="#ebhwjd">
          <%= image_tag post.image.url(:thumb), class: 'mini-img-class' if post.image? %>
          <div class="profile-post-data">
            <h3><%= link_to post.title, post_path(post) %></h3>

            <h5><%= link_to t('common.author'), user_url(post.owner_id) %></h5> <!-- Добавь тут Юзера а не протсо слово автор -->
            <div class="price">
              <p><%= post.price %> PLN</p>
              <small><%= post.created_at %></small>
            </div>
            <div class="block-with-text">
                  <%= post.body %>
            </div>

            
          </div>
        </div>
  <%end%>
<% end %>